export { ReactComponent as CrossIcon } from './icons/cross.svg';
export { ReactComponent as GearIcon } from './icons/gear.svg';
export { ReactComponent as TwitterIcon } from './icons/twitter.svg';
export { ReactComponent as GithubIcon } from './icons/github.svg';
export { ReactComponent as GithubMarkWhite } from './icons/github-mark-white.svg'
export { ReactComponent as GithubMark } from './icons/github-mark.svg'
export { ReactComponent as DiscordIcon } from './icons/discord.svg';
export { ReactComponent as MediumIcon } from './icons/medium.svg';
export { ReactComponent as VaraLogoIcon } from './icons/vara-logo.svg';
export { ReactComponent as ChevronDown } from './icons/chevron-down.svg';
export { ReactComponent as ChevronLeft } from './icons/chevron-left.svg';
export { ReactComponent as ChevronsLeft } from './icons/chevrons-left.svg';
export { ReactComponent as ChevronRight } from './icons/chevron-right.svg';
export { ReactComponent as ChevronsRight } from './icons/chevrons-right.svg';
export { ReactComponent as CaretDown } from './icons/caret-down.svg';
export { ReactComponent as CopyDecoded } from './icons/copy-decoded.svg';
export { ReactComponent as AvaVaraBlack } from './icons/ava-vara-black.svg';
export { ReactComponent as CopyIcon } from './icons/copy_icon.svg';
export { ReactComponent as CorrectIcon } from './icons/correct_copy_icon.svg';
export { ReactComponent as GreenCorrectIcon } from './icons/correct_icon_green.svg';
export { ReactComponent as AddIcon } from './icons/add_icon.svg';